# Generated by Django 4.0.4 on 2022-04-21 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mini_bio', models.TextField(max_length=500, null=True)),
                ('main_bio', models.TextField(max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Re-scheduled', 'Rescheduled'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('communication_prefrence', models.CharField(blank=True, choices=[('Text', 'Text'), ('Email', 'Email')], max_length=50)),
                ('bookings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('tattoo_color_choices', models.CharField(blank=True, choices=[('Black and White', 'Black and White'), ('Full Color', 'Full Color'), ('Other', 'Other')], max_length=50)),
                ('tattoo_size', models.CharField(max_length=200)),
                ('tattoo_placement', models.CharField(max_length=200)),
                ('tattoo_concept', models.CharField(max_length=500)),
                ('image_refrence', models.ImageField(blank=True, null=True, upload_to='')),
                ('workaround_existing_tattoos', models.TextField(max_length=500, null=True)),
                ('existing_tattoos_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('preferred_days', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200)),
                ('preferred_time_of_day', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=200)),
                ('additional_comments', models.TextField(max_length=3000, null=True)),
                ('consult_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('More Info', 'More Info'), ('Referred to another Artist', 'Referred'), ('Scheduled and ', 'Scheduled and Deposit Paid')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('categories', models.CharField(blank=True, choices=[('Traditional', 'Traditional'), ('Old School', 'Old School'), ('Neo-Traditional', 'Neo-Traditional'), ('Tribal', 'Tribal'), ('Watercolor', 'Watercolor'), ('Blackwork', 'Blackwork'), ('Realism', 'Realism'), ('Geometric', 'Geometric')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.TextField(max_length=200)),
                ('sender_phone_number', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receipient_name', models.TextField(max_length=200)),
                ('receipient_phone_number', models.CharField(max_length=200)),
                ('receipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.IntegerField()),
                ('code', models.CharField(default=uuid.uuid4, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='MerchItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('desc', models.TextField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('type', models.CharField(blank=True, choices=[('Apparel', 'Apparel'), ('Prints', 'Prints'), ('Digital Art', 'Digital Art'), ('Sticker', 'Sticker')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.IntegerField()),
                ('code', models.CharField(default=uuid.uuid4, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('availability_type', models.CharField(blank=True, choices=[('Drawing', 'Drawing'), ('Tattoing', 'Tattoing'), ('Consultation', 'Consulation'), ('Meeting', 'Meeting'), ('Learning', 'Learning'), ('Managing', 'Managing'), ('Customer Service', 'Customer Service'), ('General', 'General'), ('Other', 'Other')], max_length=50)),
                ('day_of_the_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('artist_refrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.artistinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('client_refrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
                ('promotion_refrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='consultations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_refrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='consultation_refrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gift_certificate_refrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.giftcertificate'),
        ),
    ]
