# Generated by Django 4.0.4 on 2022-04-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_first_name_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='first_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='last_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='receipient_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='receipient_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='sender_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='sender_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
