# Generated by Django 4.0.4 on 2022-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_faq_delete_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistinfo',
            old_name='main_bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='mini_bio',
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
